# 1. Imports

In [1]:
import polars as pl
import fsspec
import io
from pathlib import Path

# 2. conexão SFTP

In [2]:
fs = fsspec.filesystem(
    "sftp",
    host="localhost",
    port=2222,
    username="teste",
    password="teste"
)

## 2.1 Cria o direorio destino dos arquivos para os arquivos baixados do SFTP

In [3]:
REMOTE_PATH = "/upload/data"
LOCAL_PATH = Path("datasets/raw")
LOCAL_PATH.mkdir(parents=True, exist_ok=True)

## 2.2 Baixa os arquivos

In [4]:
for remote_file in fs.find(REMOTE_PATH):
    if fs.isdir(remote_file):
        continue

    relative_path = remote_file.replace(REMOTE_PATH, "").lstrip("/")
    local_file = LOCAL_PATH / relative_path

    local_file.parent.mkdir(parents=True, exist_ok=True)

    print(f"Baixando: {remote_file} -> {local_file}")

    with fs.open(remote_file, "rb") as src:
        content = src.read()

    with open(local_file, "wb") as dst:
        dst.write(content)

print("Download finalizado")

Baixando: /upload/data/clientes/clientes_00001.csv -> datasets/raw/clientes/clientes_00001.csv
Baixando: /upload/data/clientes/clientes_00002.csv -> datasets/raw/clientes/clientes_00002.csv
Baixando: /upload/data/clientes/clientes_00003.csv -> datasets/raw/clientes/clientes_00003.csv
Baixando: /upload/data/produtos/produtos_00001.csv -> datasets/raw/produtos/produtos_00001.csv
Baixando: /upload/data/vendas/vendas_00001.csv -> datasets/raw/vendas/vendas_00001.csv
Baixando: /upload/data/vendas/vendas_00002.csv -> datasets/raw/vendas/vendas_00002.csv
Baixando: /upload/data/vendas/vendas_00003.csv -> datasets/raw/vendas/vendas_00003.csv
Baixando: /upload/data/vendas/vendas_00004.csv -> datasets/raw/vendas/vendas_00004.csv
Baixando: /upload/data/vendas/vendas_00005.csv -> datasets/raw/vendas/vendas_00005.csv
Baixando: /upload/data/vendas/vendas_00006.csv -> datasets/raw/vendas/vendas_00006.csv
Download finalizado

# 3. Tratando os dados

In [5]:
# Pasta onde os arquivos baixados estão
BASE_PATH = "datasets/raw"

## 3.1 Carregando os dados baixados do SFTP com polars

In [6]:
clientes = pl.scan_csv(
    f"{BASE_PATH}/clientes/*.csv",
    separator=",",
    encoding="utf8"
)

produtos = pl.scan_csv(
    f"{BASE_PATH}/produtos/*.csv",
    separator=",",
    encoding="utf8"
)

vendas = pl.scan_csv(
    f"{BASE_PATH}/vendas/*.csv",
    separator=",",
    encoding="utf8"
)


clientes = clientes.collect()
produtos = produtos.collect()
vendas = vendas.collect()

## 3.2 Tratando tabela clientes

In [7]:
clientes.head()

shape: (5, 6)
┌────────────┬─────────────────┬────────────────┬────────┬───────────────┬─────────────────────────┐
│ id_cliente ┆ nome            ┆ cidade         ┆ estado ┆ data_cadastro ┆ interesses              │
│ ---        ┆ ---             ┆ ---            ┆ ---    ┆ ---           ┆ ---                     │
│ i64        ┆ str             ┆ str            ┆ str    ┆ str           ┆ str                     │
╞════════════╪═════════════════╪════════════════╪════════╪═══════════════╪═════════════════════════╡
│ 1          ┆ Vanessa Souza   ┆ São Paulo      ┆ SP     ┆ 2022-05-04    ┆ ["viagem", "financas"]  │
│            ┆                 ┆                ┆        ┆ 11:40:21      ┆                         │
│ 2          ┆ Daniela Martins ┆ Rio de Janeiro ┆ RJ     ┆ 2025-01-08    ┆ ["esportes", "moda",    │
│            ┆                 ┆                ┆        ┆ 14:18:46      ┆ "tecnolog…              │
│ 3          ┆ Helena Ribeiro  ┆ São Paulo      ┆ SP     ┆ 2024-10-09    ┆ ["moda", "livros"]      │
│            ┆                 ┆                ┆        ┆ 17:27:54      ┆                         │
│ 4          ┆ Nicolas Santos  ┆ Fortaleza      ┆ CE     ┆ 2025-01-04    ┆ ["esportes",            │
│            ┆                 ┆                ┆        ┆ 18:50:02      ┆ "financas", "musi…      │
│ 5          ┆ Karina Lima     ┆ Belo Horizonte ┆ MG     ┆ 2021-10-30    ┆ ["tecnologia", "moda",  │
│            ┆                 ┆                ┆        ┆ 22:57:27      ┆ "musica…                │
└────────────┴─────────────────┴────────────────┴────────┴───────────────┴─────────────────────────┘

### 3.2.1 Convertendo a coluna data_cadastro para datatime

In [8]:
clientes = clientes.with_columns(
    pl.col("data_cadastro").str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S")
)

In [9]:
clientes.head()

shape: (5, 6)
┌────────────┬─────────────────┬────────────────┬────────┬───────────────┬─────────────────────────┐
│ id_cliente ┆ nome            ┆ cidade         ┆ estado ┆ data_cadastro ┆ interesses              │
│ ---        ┆ ---             ┆ ---            ┆ ---    ┆ ---           ┆ ---                     │
│ i64        ┆ str             ┆ str            ┆ str    ┆ datetime[μs]  ┆ str                     │
╞════════════╪═════════════════╪════════════════╪════════╪═══════════════╪═════════════════════════╡
│ 1          ┆ Vanessa Souza   ┆ São Paulo      ┆ SP     ┆ 2022-05-04    ┆ ["viagem", "financas"]  │
│            ┆                 ┆                ┆        ┆ 11:40:21      ┆                         │
│ 2          ┆ Daniela Martins ┆ Rio de Janeiro ┆ RJ     ┆ 2025-01-08    ┆ ["esportes", "moda",    │
│            ┆                 ┆                ┆        ┆ 14:18:46      ┆ "tecnolog…              │
│ 3          ┆ Helena Ribeiro  ┆ São Paulo      ┆ SP     ┆ 2024-10-09    ┆ ["moda", "livros"]      │
│            ┆                 ┆                ┆        ┆ 17:27:54      ┆                         │
│ 4          ┆ Nicolas Santos  ┆ Fortaleza      ┆ CE     ┆ 2025-01-04    ┆ ["esportes",            │
│            ┆                 ┆                ┆        ┆ 18:50:02      ┆ "financas", "musi…      │
│ 5          ┆ Karina Lima     ┆ Belo Horizonte ┆ MG     ┆ 2021-10-30    ┆ ["tecnologia", "moda",  │
│            ┆                 ┆                ┆        ┆ 22:57:27      ┆ "musica…                │
└────────────┴─────────────────┴────────────────┴────────┴───────────────┴─────────────────────────┘

### 3.2.2 Explodindo a coluna insteresses

In [10]:
clientes = clientes.with_columns(
    pl.col("interesses").str.json_decode(pl.List(pl.Utf8))
)

In [11]:
clientes.head()

shape: (5, 6)
┌────────────┬─────────────────┬────────────────┬────────┬───────────────┬─────────────────────────┐
│ id_cliente ┆ nome            ┆ cidade         ┆ estado ┆ data_cadastro ┆ interesses              │
│ ---        ┆ ---             ┆ ---            ┆ ---    ┆ ---           ┆ ---                     │
│ i64        ┆ str             ┆ str            ┆ str    ┆ datetime[μs]  ┆ list[str]               │
╞════════════╪═════════════════╪════════════════╪════════╪═══════════════╪═════════════════════════╡
│ 1          ┆ Vanessa Souza   ┆ São Paulo      ┆ SP     ┆ 2022-05-04    ┆ ["viagem", "financas"]  │
│            ┆                 ┆                ┆        ┆ 11:40:21      ┆                         │
│ 2          ┆ Daniela Martins ┆ Rio de Janeiro ┆ RJ     ┆ 2025-01-08    ┆ ["esportes", "moda", …  │
│            ┆                 ┆                ┆        ┆ 14:18:46      ┆ "viagem…                │
│ 3          ┆ Helena Ribeiro  ┆ São Paulo      ┆ SP     ┆ 2024-10-09    ┆ ["moda", "livros"]      │
│            ┆                 ┆                ┆        ┆ 17:27:54      ┆                         │
│ 4          ┆ Nicolas Santos  ┆ Fortaleza      ┆ CE     ┆ 2025-01-04    ┆ ["esportes",            │
│            ┆                 ┆                ┆        ┆ 18:50:02      ┆ "financas", "musi…      │
│ 5          ┆ Karina Lima     ┆ Belo Horizonte ┆ MG     ┆ 2021-10-30    ┆ ["tecnologia", "moda",  │
│            ┆                 ┆                ┆        ┆ 22:57:27      ┆ "musica…                │
└────────────┴─────────────────┴────────────────┴────────┴───────────────┴─────────────────────────┘

In [12]:
clientes_explodidos_interesses = clientes.explode("interesses")

In [13]:
clientes_explodidos_interesses.head()

shape: (5, 6)
┌────────────┬─────────────────┬────────────────┬────────┬─────────────────────┬────────────┐
│ id_cliente ┆ nome            ┆ cidade         ┆ estado ┆ data_cadastro       ┆ interesses │
│ ---        ┆ ---             ┆ ---            ┆ ---    ┆ ---                 ┆ ---        │
│ i64        ┆ str             ┆ str            ┆ str    ┆ datetime[μs]        ┆ str        │
╞════════════╪═════════════════╪════════════════╪════════╪═════════════════════╪════════════╡
│ 1          ┆ Vanessa Souza   ┆ São Paulo      ┆ SP     ┆ 2022-05-04 11:40:21 ┆ viagem     │
│ 1          ┆ Vanessa Souza   ┆ São Paulo      ┆ SP     ┆ 2022-05-04 11:40:21 ┆ financas   │
│ 2          ┆ Daniela Martins ┆ Rio de Janeiro ┆ RJ     ┆ 2025-01-08 14:18:46 ┆ esportes   │
│ 2          ┆ Daniela Martins ┆ Rio de Janeiro ┆ RJ     ┆ 2025-01-08 14:18:46 ┆ moda       │
│ 2          ┆ Daniela Martins ┆ Rio de Janeiro ┆ RJ     ┆ 2025-01-08 14:18:46 ┆ tecnologia │
└────────────┴─────────────────┴────────────────┴────────┴─────────────────────┴────────────┘

## 3.3 Tratando tabela de vendas

In [14]:
vendas.head()

shape: (5, 7)
┌──────────┬────────────┬────────────┬────────────┬────────────┬────────────────┬─────────────┐
│ id_venda ┆ id_cliente ┆ id_produto ┆ data_venda ┆ quantidade ┆ valor_unitario ┆ valor_total │
│ ---      ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---            ┆ ---         │
│ i64      ┆ i64        ┆ i64        ┆ str        ┆ i64        ┆ f64            ┆ f64         │
╞══════════╪════════════╪════════════╪════════════╪════════════╪════════════════╪═════════════╡
│ 1        ┆ 6432       ┆ 4472       ┆ 2024-09-20 ┆ 8          ┆ 2079.22        ┆ 16633.76    │
│          ┆            ┆            ┆ 22:53:45   ┆            ┆                ┆             │
│ 2        ┆ 119141     ┆ 12608      ┆ 2025-09-03 ┆ 1          ┆ 296.05         ┆ 296.05      │
│          ┆            ┆            ┆ 17:59:52   ┆            ┆                ┆             │
│ 3        ┆ 97636      ┆ 1923       ┆ 2023-09-25 ┆ 8          ┆ 1582.77        ┆ 12662.16    │
│          ┆            ┆            ┆ 00:50:49   ┆            ┆                ┆             │
│ 4        ┆ 103877     ┆ 13257      ┆ 2023-01-04 ┆ 1          ┆ 1349.23        ┆ 1349.23     │
│          ┆            ┆            ┆ 07:31:15   ┆            ┆                ┆             │
│ 5        ┆ 117612     ┆ 12238      ┆ 2025-08-23 ┆ 6          ┆ 1454.36        ┆ 8726.16     │
│          ┆            ┆            ┆ 19:43:50   ┆            ┆                ┆             │
└──────────┴────────────┴────────────┴────────────┴────────────┴────────────────┴─────────────┘

### 3.3.1 Convertendo a coluna data_venda para datatime

In [15]:
vendas = vendas.with_columns(
    pl.col("data_venda").str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S")
)

In [16]:
vendas.head()

shape: (5, 7)
┌──────────┬────────────┬────────────┬─────────────────┬────────────┬────────────────┬─────────────┐
│ id_venda ┆ id_cliente ┆ id_produto ┆ data_venda      ┆ quantidade ┆ valor_unitario ┆ valor_total │
│ ---      ┆ ---        ┆ ---        ┆ ---             ┆ ---        ┆ ---            ┆ ---         │
│ i64      ┆ i64        ┆ i64        ┆ datetime[μs]    ┆ i64        ┆ f64            ┆ f64         │
╞══════════╪════════════╪════════════╪═════════════════╪════════════╪════════════════╪═════════════╡
│ 1        ┆ 6432       ┆ 4472       ┆ 2024-09-20      ┆ 8          ┆ 2079.22        ┆ 16633.76    │
│          ┆            ┆            ┆ 22:53:45        ┆            ┆                ┆             │
│ 2        ┆ 119141     ┆ 12608      ┆ 2025-09-03      ┆ 1          ┆ 296.05         ┆ 296.05      │
│          ┆            ┆            ┆ 17:59:52        ┆            ┆                ┆             │
│ 3        ┆ 97636      ┆ 1923       ┆ 2023-09-25      ┆ 8          ┆ 1582.77        ┆ 12662.16    │
│          ┆            ┆            ┆ 00:50:49        ┆            ┆                ┆             │
│ 4        ┆ 103877     ┆ 13257      ┆ 2023-01-04      ┆ 1          ┆ 1349.23        ┆ 1349.23     │
│          ┆            ┆            ┆ 07:31:15        ┆            ┆                ┆             │
│ 5        ┆ 117612     ┆ 12238      ┆ 2025-08-23      ┆ 6          ┆ 1454.36        ┆ 8726.16     │
│          ┆            ┆            ┆ 19:43:50        ┆            ┆                ┆             │
└──────────┴────────────┴────────────┴─────────────────┴────────────┴────────────────┴─────────────┘

## 3.4 Fazendo Joins entre tabelas

### 3.4.1 Join entre vendas e clientes

In [17]:
vendas.head()

shape: (5, 7)
┌──────────┬────────────┬────────────┬─────────────────┬────────────┬────────────────┬─────────────┐
│ id_venda ┆ id_cliente ┆ id_produto ┆ data_venda      ┆ quantidade ┆ valor_unitario ┆ valor_total │
│ ---      ┆ ---        ┆ ---        ┆ ---             ┆ ---        ┆ ---            ┆ ---         │
│ i64      ┆ i64        ┆ i64        ┆ datetime[μs]    ┆ i64        ┆ f64            ┆ f64         │
╞══════════╪════════════╪════════════╪═════════════════╪════════════╪════════════════╪═════════════╡
│ 1        ┆ 6432       ┆ 4472       ┆ 2024-09-20      ┆ 8          ┆ 2079.22        ┆ 16633.76    │
│          ┆            ┆            ┆ 22:53:45        ┆            ┆                ┆             │
│ 2        ┆ 119141     ┆ 12608      ┆ 2025-09-03      ┆ 1          ┆ 296.05         ┆ 296.05      │
│          ┆            ┆            ┆ 17:59:52        ┆            ┆                ┆             │
│ 3        ┆ 97636      ┆ 1923       ┆ 2023-09-25      ┆ 8          ┆ 1582.77        ┆ 12662.16    │
│          ┆            ┆            ┆ 00:50:49        ┆            ┆                ┆             │
│ 4        ┆ 103877     ┆ 13257      ┆ 2023-01-04      ┆ 1          ┆ 1349.23        ┆ 1349.23     │
│          ┆            ┆            ┆ 07:31:15        ┆            ┆                ┆             │
│ 5        ┆ 117612     ┆ 12238      ┆ 2025-08-23      ┆ 6          ┆ 1454.36        ┆ 8726.16     │
│          ┆            ┆            ┆ 19:43:50        ┆            ┆                ┆             │
└──────────┴────────────┴────────────┴─────────────────┴────────────┴────────────────┴─────────────┘

In [18]:
clientes.head()

shape: (5, 6)
┌────────────┬─────────────────┬────────────────┬────────┬───────────────┬─────────────────────────┐
│ id_cliente ┆ nome            ┆ cidade         ┆ estado ┆ data_cadastro ┆ interesses              │
│ ---        ┆ ---             ┆ ---            ┆ ---    ┆ ---           ┆ ---                     │
│ i64        ┆ str             ┆ str            ┆ str    ┆ datetime[μs]  ┆ list[str]               │
╞════════════╪═════════════════╪════════════════╪════════╪═══════════════╪═════════════════════════╡
│ 1          ┆ Vanessa Souza   ┆ São Paulo      ┆ SP     ┆ 2022-05-04    ┆ ["viagem", "financas"]  │
│            ┆                 ┆                ┆        ┆ 11:40:21      ┆                         │
│ 2          ┆ Daniela Martins ┆ Rio de Janeiro ┆ RJ     ┆ 2025-01-08    ┆ ["esportes", "moda", …  │
│            ┆                 ┆                ┆        ┆ 14:18:46      ┆ "viagem…                │
│ 3          ┆ Helena Ribeiro  ┆ São Paulo      ┆ SP     ┆ 2024-10-09    ┆ ["moda", "livros"]      │
│            ┆                 ┆                ┆        ┆ 17:27:54      ┆                         │
│ 4          ┆ Nicolas Santos  ┆ Fortaleza      ┆ CE     ┆ 2025-01-04    ┆ ["esportes",            │
│            ┆                 ┆                ┆        ┆ 18:50:02      ┆ "financas", "musi…      │
│ 5          ┆ Karina Lima     ┆ Belo Horizonte ┆ MG     ┆ 2021-10-30    ┆ ["tecnologia", "moda",  │
│            ┆                 ┆                ┆        ┆ 22:57:27      ┆ "musica…                │
└────────────┴─────────────────┴────────────────┴────────┴───────────────┴─────────────────────────┘

In [19]:
vendas_clientes = vendas.join(clientes,
how='left',
on='id_cliente')

In [20]:
vendas_clientes.head()

shape: (5, 12)
┌──────────┬────────────┬────────────┬────────────┬───┬───────────┬────────┬───────────┬───────────┐
│ id_venda ┆ id_cliente ┆ id_produto ┆ data_venda ┆ … ┆ cidade    ┆ estado ┆ data_cada ┆ interesse │
│ ---      ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---       ┆ ---    ┆ stro      ┆ s         │
│ i64      ┆ i64        ┆ i64        ┆ datetime[μ ┆   ┆ str       ┆ str    ┆ ---       ┆ ---       │
│          ┆            ┆            ┆ s]         ┆   ┆           ┆        ┆ datetime[ ┆ list[str] │
│          ┆            ┆            ┆            ┆   ┆           ┆        ┆ μs]       ┆           │
╞══════════╪════════════╪════════════╪════════════╪═══╪═══════════╪════════╪═══════════╪═══════════╡
│ 1        ┆ 6432       ┆ 4472       ┆ 2024-09-20 ┆ … ┆ Niterói   ┆ RJ     ┆ 2023-05-0 ┆ ["moda",  │
│          ┆            ┆            ┆ 22:53:45   ┆   ┆           ┆        ┆ 2         ┆ "musica"] │
│          ┆            ┆            ┆            ┆   ┆           ┆        ┆ 10:19:38  ┆           │
│ 2        ┆ 119141     ┆ 12608      ┆ 2025-09-03 ┆ … ┆ Recife    ┆ PE     ┆ 2024-05-3 ┆ ["musica" │
│          ┆            ┆            ┆ 17:59:52   ┆   ┆           ┆        ┆ 1         ┆ , "culina │
│          ┆            ┆            ┆            ┆   ┆           ┆        ┆ 05:32:12  ┆ ria",     │
│          ┆            ┆            ┆            ┆   ┆           ┆        ┆           ┆ "fitne…   │
│ 3        ┆ 97636      ┆ 1923       ┆ 2023-09-25 ┆ … ┆ Curitiba  ┆ PR     ┆ 2025-07-0 ┆ ["filmes" │
│          ┆            ┆            ┆ 00:50:49   ┆   ┆           ┆        ┆ 1         ┆ ]         │
│          ┆            ┆            ┆            ┆   ┆           ┆        ┆ 22:43:23  ┆           │
│ 4        ┆ 103877     ┆ 13257      ┆ 2023-01-04 ┆ … ┆ Niterói   ┆ RJ     ┆ 2025-12-0 ┆ ["fitness │
│          ┆            ┆            ┆ 07:31:15   ┆   ┆           ┆        ┆ 9         ┆ "]        │
│          ┆            ┆            ┆            ┆   ┆           ┆        ┆ 08:21:07  ┆           │
│ 5        ┆ 117612     ┆ 12238      ┆ 2025-08-23 ┆ … ┆ São Paulo ┆ SP     ┆ 2024-08-1 ┆ ["culinar │
│          ┆            ┆            ┆ 19:43:50   ┆   ┆           ┆        ┆ 7         ┆ ia",      │
│          ┆            ┆            ┆            ┆   ┆           ┆        ┆ 12:45:20  ┆ "livros", │
│          ┆            ┆            ┆            ┆   ┆           ┆        ┆           ┆ … "via…   │
└──────────┴────────────┴────────────┴────────────┴───┴───────────┴────────┴───────────┴───────────┘

### #.4.2 Join entre vendas_clientes com produtos

In [21]:
vendas_clientes.head()

shape: (5, 12)
┌──────────┬────────────┬────────────┬────────────┬───┬───────────┬────────┬───────────┬───────────┐
│ id_venda ┆ id_cliente ┆ id_produto ┆ data_venda ┆ … ┆ cidade    ┆ estado ┆ data_cada ┆ interesse │
│ ---      ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---       ┆ ---    ┆ stro      ┆ s         │
│ i64      ┆ i64        ┆ i64        ┆ datetime[μ ┆   ┆ str       ┆ str    ┆ ---       ┆ ---       │
│          ┆            ┆            ┆ s]         ┆   ┆           ┆        ┆ datetime[ ┆ list[str] │
│          ┆            ┆            ┆            ┆   ┆           ┆        ┆ μs]       ┆           │
╞══════════╪════════════╪════════════╪════════════╪═══╪═══════════╪════════╪═══════════╪═══════════╡
│ 1        ┆ 6432       ┆ 4472       ┆ 2024-09-20 ┆ … ┆ Niterói   ┆ RJ     ┆ 2023-05-0 ┆ ["moda",  │
│          ┆            ┆            ┆ 22:53:45   ┆   ┆           ┆        ┆ 2         ┆ "musica"] │
│          ┆            ┆            ┆            ┆   ┆           ┆        ┆ 10:19:38  ┆           │
│ 2        ┆ 119141     ┆ 12608      ┆ 2025-09-03 ┆ … ┆ Recife    ┆ PE     ┆ 2024-05-3 ┆ ["musica" │
│          ┆            ┆            ┆ 17:59:52   ┆   ┆           ┆        ┆ 1         ┆ , "culina │
│          ┆            ┆            ┆            ┆   ┆           ┆        ┆ 05:32:12  ┆ ria",     │
│          ┆            ┆            ┆            ┆   ┆           ┆        ┆           ┆ "fitne…   │
│ 3        ┆ 97636      ┆ 1923       ┆ 2023-09-25 ┆ … ┆ Curitiba  ┆ PR     ┆ 2025-07-0 ┆ ["filmes" │
│          ┆            ┆            ┆ 00:50:49   ┆   ┆           ┆        ┆ 1         ┆ ]         │
│          ┆            ┆            ┆            ┆   ┆           ┆        ┆ 22:43:23  ┆           │
│ 4        ┆ 103877     ┆ 13257      ┆ 2023-01-04 ┆ … ┆ Niterói   ┆ RJ     ┆ 2025-12-0 ┆ ["fitness │
│          ┆            ┆            ┆ 07:31:15   ┆   ┆           ┆        ┆ 9         ┆ "]        │
│          ┆            ┆            ┆            ┆   ┆           ┆        ┆ 08:21:07  ┆           │
│ 5        ┆ 117612     ┆ 12238      ┆ 2025-08-23 ┆ … ┆ São Paulo ┆ SP     ┆ 2024-08-1 ┆ ["culinar │
│          ┆            ┆            ┆ 19:43:50   ┆   ┆           ┆        ┆ 7         ┆ ia",      │
│          ┆            ┆            ┆            ┆   ┆           ┆        ┆ 12:45:20  ┆ "livros", │
│          ┆            ┆            ┆            ┆   ┆           ┆        ┆           ┆ … "via…   │
└──────────┴────────────┴────────────┴────────────┴───┴───────────┴────────┴───────────┴───────────┘

In [22]:
produtos.head()

shape: (5, 4)
┌────────────┬───────────────────┬─────────────┬────────────────┐
│ id_produto ┆ nome_produto      ┆ categoria   ┆ preco_unitario │
│ ---        ┆ ---               ┆ ---         ┆ ---            │
│ i64        ┆ str               ┆ str         ┆ f64            │
╞════════════╪═══════════════════╪═════════════╪════════════════╡
│ 1          ┆ Cadeira 1         ┆ Automotivo  ┆ 3531.82        │
│ 2          ┆ Notebook 2        ┆ Livros      ┆ 47.34          │
│ 3          ┆ Notebook 3        ┆ Casa        ┆ 4224.35        │
│ 4          ┆ Garrafa Térmica 4 ┆ Informática ┆ 3263.52        │
│ 5          ┆ Liquidificador 5  ┆ Casa        ┆ 2051.46        │
└────────────┴───────────────────┴─────────────┴────────────────┘

In [23]:
vendas_clientes_produtos = vendas_clientes.join(
    produtos,
    how='inner',
    on="id_produto"
)

In [24]:
vendas_clientes_produtos.head()

shape: (5, 15)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id_venda ┆ id_client ┆ id_produt ┆ data_vend ┆ … ┆ interesse ┆ nome_prod ┆ categoria ┆ preco_uni │
│ ---      ┆ e         ┆ o         ┆ a         ┆   ┆ s         ┆ uto       ┆ ---       ┆ tario     │
│ i64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---       │
│          ┆ i64       ┆ i64       ┆ datetime[ ┆   ┆ list[str] ┆ str       ┆           ┆ f64       │
│          ┆           ┆           ┆ μs]       ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 6432      ┆ 4472      ┆ 2024-09-2 ┆ … ┆ ["moda",  ┆ Garrafa   ┆ Escritóri ┆ 4741.32   │
│          ┆           ┆           ┆ 0         ┆   ┆ "musica"] ┆ Térmica   ┆ o         ┆           │
│          ┆           ┆           ┆ 22:53:45  ┆   ┆           ┆ 4472      ┆           ┆           │
│ 2        ┆ 119141    ┆ 12608     ┆ 2025-09-0 ┆ … ┆ ["musica" ┆ Livro     ┆ Casa      ┆ 2961.94   │
│          ┆           ┆           ┆ 3         ┆   ┆ , "culina ┆ Técnico   ┆           ┆           │
│          ┆           ┆           ┆ 17:59:52  ┆   ┆ ria",     ┆ 12608     ┆           ┆           │
│          ┆           ┆           ┆           ┆   ┆ "fitne…   ┆           ┆           ┆           │
│ 3        ┆ 97636     ┆ 1923      ┆ 2023-09-2 ┆ … ┆ ["filmes" ┆ Teclado   ┆ Escritóri ┆ 852.6     │
│          ┆           ┆           ┆ 5         ┆   ┆ ]         ┆ 1923      ┆ o         ┆           │
│          ┆           ┆           ┆ 00:50:49  ┆   ┆           ┆           ┆           ┆           │
│ 4        ┆ 103877    ┆ 13257     ┆ 2023-01-0 ┆ … ┆ ["fitness ┆ Teclado   ┆ Cozinha   ┆ 1230.53   │
│          ┆           ┆           ┆ 4         ┆   ┆ "]        ┆ 13257     ┆           ┆           │
│          ┆           ┆           ┆ 07:31:15  ┆   ┆           ┆           ┆           ┆           │
│ 5        ┆ 117612    ┆ 12238     ┆ 2025-08-2 ┆ … ┆ ["culinar ┆ Fone      ┆ Esporte   ┆ 4486.23   │
│          ┆           ┆           ┆ 3         ┆   ┆ ia",      ┆ 12238     ┆           ┆           │
│          ┆           ┆           ┆ 19:43:50  ┆   ┆ "livros", ┆           ┆           ┆           │
│          ┆           ┆           ┆           ┆   ┆ … "via…   ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# 4. Exportando os dados

In [25]:
# cria a pasta exports em datasets
Path("datasets/exports").mkdir(parents=True, exist_ok=True)

## 4.1 CSV

In [26]:
# Para salvar em csv é necessário converter a coluna interesse que no momento é do tipo List para do tipo str (string)
vendas_clientes_produtos = vendas_clientes_produtos.with_columns(
    pl.col("interesses").list.join(", ").alias("interesses")
)

In [27]:
vendas_clientes_produtos.write_csv("datasets/exports/vendas_clientes_produtos.csv", separator=",")

## 4.2 parquet

In [28]:
vendas_clientes_produtos.write_parquet("datasets/exports/vendas_clientes_produtos.parquet")

## 4.3 Excel

In [29]:
vendas_clientes_produtos.write_excel("datasets/exports/vendas_clientes_produtos.xlsx")

## 4.4 json

In [30]:
vendas_clientes_produtos.write_json("datasets/exports/vendas_clientes_produtos.json")

# 5. Carregando no Mysql

In [32]:
import polars as pl
from sqlalchemy import create_engine
from sqlalchemy.types import Text

# converte todas as colunas para string no Polars
df = vendas_clientes_produtos.with_columns(
    [pl.col(col).cast(pl.Utf8).alias(col) for col in vendas_clientes_produtos.columns]
)

# converte para pandas
df_pd = df.to_pandas()

engine = create_engine(
    "mysql+pymysql://app_bi:12F95D9BB576440A@localhost:3306/DW_BI?charset=utf8mb4"
)

# força todas as colunas como TEXT no MySQL
tipos_sql = {col: Text() for col in df_pd.columns}

df_pd.to_sql(
    name="vendas_clientes_produtos",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=1000,
    method="multi",
    dtype=tipos_sql
)

300000

# 6. Carga no BigQuery

In [ ]:
from bq import upload_dataframe_to_bigquery

upload_dataframe_to_bigquery(
    path_file="dados/vendas.parquet",
    project_id="meu-projeto-gcp",
    target_table="meu_dataset.minha_tabela",
    credentials_path="credenciais.json",
    write_disposition="WRITE_TRUNCATE"
)